---
title: "MTCars Dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme:
      version: 3
      bootswatch: flatly
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(crosstalk)
library(DT)
library(plotly)
# library(d3scatter)
library(summarywidget)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

mtCarsSD <- mtcars |> 
  mutate(cyl = factor(cyl)) |> 
  SharedData$new()

```

Column {data-width=650 .tabset}
-----------------------------------------------------------------------

### Fuel Mileage Chart

```{r}

mtCarsSD |> 
  plot_ly(x=~hp, y=~mpg, color=~cyl) |> 
  layout(xaxis=list(title="Horsepower"),
         yaxis=list(title="Miles per Gallon"),
         legend=list(title=list(text="Cyl.")))

```

### Fuel Mileage Table

```{r}

datatable(mtCarsSD)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Filters

```{r}

filter_checkbox("cyl", "Cylinders", mtCarsSD, ~cyl, inline=T)
filter_checkbox("am", "Automatic", mtCarsSD, ~am, inline = T)
```

### Summary

Of the `r summarywidget(mtCarsSD, "count")` cars:

  - `r summarywidget(mtCarsSD, "count", selection=~am==1)` are Automatic
  - `r summarywidget(mtCarsSD, "count", selection=~am==0)` are Manual

